version: '3.8'
services:
  gc-monitor:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  load-test:
    build: 
      context: .
      dockerfile: Dockerfile.loadtest
    depends_on:
      - gc-monitor
    profiles:
      - testing
